Updates based on PR comments

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -87,6 +87,8 @@ jobs:
           - {go: "${{ needs.get-go-version.outputs.go-version }}", goos: "solaris", goarch: "amd64", component: "control-plane", pkg_name: "consul-k8s-control-plane" } 
           - {go: "${{ needs.get-go-version.outputs.go-version }}", goos: "windows", goarch: "386", component: "control-plane", pkg_name: "consul-k8s-control-plane" }
           - {go: "${{ needs.get-go-version.outputs.go-version }}", goos: "windows", goarch: "amd64", component: "control-plane", pkg_name: "consul-k8s-control-plane" }
+          - {go: "${{ needs.get-go-version.outputs.go-version }}", goos: "darwin", goarch: "amd64", component: "cli", pkg_name: "consul-k8s" }
+          - {go: "${{ needs.get-go-version.outputs.go-version }}", goos: "darwin", goarch: "amd64", component: "control-plane", pkg_name: "consul-k8s-control-plane" }
       fail-fast: true
 
     name: Go ${{ matrix.go }} ${{ matrix.goos }} ${{ matrix.goarch }} ${{ matrix.component }} build    
@@ -116,7 +118,7 @@ jobs:
           path: ${{ matrix.component}}/out/${{ matrix.pkg_name }}_${{ needs.get-product-version.outputs.product-version }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
             
       - name: Package rpm and deb files 
-        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' }}
+        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' && matrix.goarch == 'amd64'}}
         uses: hashicorp/actions-packaging-linux@v1
         with:
           name: consul-k8s 
@@ -131,58 +133,60 @@ jobs:
           rpm_depends: "openssl"
 
       - name: Set package names
-        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' }}
+        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' && matrix.goarch == 'amd64'}}
         run: |
           echo "RPM_PACKAGE=$(basename out/*.rpm)" >> $GITHUB_ENV
           echo "DEB_PACKAGE=$(basename out/*.deb)" >> $GITHUB_ENV
 
-      - name: Upload rpm packages 
+      - name: Test rpm package
+        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' && matrix.goarch == 'amd64'}}
+        uses: addnab/docker-run-action@v3
+        with:
+          image: registry.access.redhat.com/ubi8/ubi:latest
+          options: -v ${{ github.workspace }}:/work
+          run: |
+            dnf install -qy openssl
+            cd /work
+            rpm -ivh out/${{ env.RPM_PACKAGE }}
+            CONSUL_K8S_VERSION="$(consul-k8s version | awk '{print $2}')"
+            VERSION="${{ needs.get-product-version.outputs.product-version }}"
+            if [ "${VERSION}" != "${CONSUL_K8S_VERSION}" ]; then
+              echo "Test FAILED, expected: ${VERSION}, got: ${CONSUL_K8S_VERSION}"
+              exit 1
+            fi
+            echo "Test PASSED, expected: ${VERSION}, got: ${CONSUL_K8S_VERSION}"
+
+      - name: Upload rpm package
         uses: actions/upload-artifact@v2
-        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' }}
+        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' && matrix.goarch == 'amd64'}}
         with:
           name: ${{ env.RPM_PACKAGE }}
           path: out/${{ env.RPM_PACKAGE }}
 
+      - name: Test debian package
+        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' && matrix.goarch == 'amd64'}}
+        uses: addnab/docker-run-action@v3
+        with:
+          image: ubuntu:latest
+          options: -v ${{ github.workspace }}:/work
+          run: |
+            apt update && apt install -y openssl
+            cd /work
+            apt install ./out/${{ env.DEB_PACKAGE }}
+            CONSUL_K8S_VERSION="$(consul-k8s version | awk '{print $2}')"
+            VERSION="${{ needs.get-product-version.outputs.product-version }}"
+            if [ "${VERSION}" != "${CONSUL_K8S_VERSION}" ]; then
+              echo "Test FAILED, expected: ${VERSION}, got: ${CONSUL_K8S_VERSION}"
+              exit 1
+            fi
+            echo "Test PASSED, expected: ${VERSION}, got: ${CONSUL_K8S_VERSION}"
+
       - name: Upload debian packages 
         uses: actions/upload-artifact@v2
-        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' }}
+        if: ${{ matrix.goos == 'linux' && matrix.component == 'cli' && matrix.goarch == 'amd64'}}
         with:
           name: ${{ env.DEB_PACKAGE }}
           path: out/${{ env.DEB_PACKAGE }}
-
-  build-darwin:
-    needs: [get-go-version, get-product-version]
-    runs-on: macos-latest
-    strategy:
-      matrix:
-        include:
-          - {go: "${{ needs.get-go-version.outputs.go-version }}", goos: "darwin", goarch: "amd64", component: "cli", pkg_name: "consul-k8s" }
-          - {go: "${{ needs.get-go-version.outputs.go-version }}", goos: "darwin", goarch: "amd64", component: "control-plane", pkg_name: "consul-k8s-control-plane" }
-      fail-fast: true
-
-    name: Go ${{ matrix.go }} ${{ matrix.goos }} ${{ matrix.goarch }} ${{ matrix.component }} build
-    env:
-      GOOS: ${{ matrix.goos }}
-      GOARCH: ${{ matrix.goarch }}
-      CGO_ENABLED: 0
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Setup go
-        uses: actions/setup-go@v2
-        with:
-          go-version: ${{ matrix.go }}
-
-      - name: Build
-        working-directory: ${{ matrix.component }}
-        run: |
-          mkdir -p dist out
-          go build -tags netcgo -o dist/${{ matrix.pkg_name }} .
-          zip -r -j out/${{ matrix.pkg_name }}_${{ needs.get-product-version.outputs.product-version }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip dist/
-      - uses: actions/upload-artifact@v3
-        with:
-          name: ${{ matrix.pkg_name  }}_${{ needs.get-product-version.outputs.product-version }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
-          path: ${{ matrix.component}}/out/${{ matrix.pkg_name }}_${{ needs.get-product-version.outputs.product-version }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip
 
   build-docker-default:
     name: Docker ${{ matrix.arch }} default release build
@@ -245,15 +249,14 @@ jobs:
             fi
             echo "Test PASSED"
           version: ${{ env.version }}
-          target: release-alternate
+          target: ubi 
           arch: ${{ matrix.arch }}
           pkg_name: consul-k8s-control-plane_${{ env.version }}
           bin_name: consul-k8s-control-plane 
           workdir: control-plane
           tags: |
-            docker.io/hashicorp/${{ env.repo }}-control-plane-ubi:${{ env.version }}
-            986891699432.dkr.ecr.us-east-1.amazonaws.com/hashicorp/${{ env.repo }}-control-plane-ubi:${{ env.version }}
+            registry.connect.redhat.com/hashicorp/consul-k8s-control-plane:${{env.version}}-ubi
           dev_tags: |
-            hashicorppreview/${{ env.repo }}-control-plane-ubi:${{ env.version }}-dev
-            docker.io/hashicorppreview/${{ env.repo }}-control-plane-ubi:${{ env.version }}-${{ github.sha }}
+            hashicorppreview/${{ env.repo }}-control-plane:${{ env.version }}-ubi-dev
+            docker.io/hashicorppreview/${{ env.repo }}-control-plane:${{ env.version }}-ubi-${{ github.sha }}
 
